[git_status]
format = '[$stashed$conflicted$modified$staged$untracked$ahead_behind](yellow bold)'
ahead = '⇡${count} '
diverged = '⇡${ahead_count}⇣${behind_count} '
behind = '⇣${count} '
stashed = '*${count} '
conflicted = '~${count} '
staged = '+${count} '
untracked = '?${count} '
modified = '!${count} '

[container]
symbol = ''
format = '[$symbol  $name]($style) '
style = 'bold blue'

